language: node_js
node_js:
- 6
before_install:
- openssl aes-256-cbc -K $encrypted_a259f50740b9_key -iv $encrypted_a259f50740b9_iv
  -in src/private.tar.enc -out src/private.tar -d
- tar xvf src/private.tar -C src
install:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: VQbZOCU+pvsunSmAMl9xQTFB29HFQMFNbmPzdCfseWWaf/VMUwbQZRH0Gx4SzhonrjHbSJOll4ak4LAH8rJoiKKQ9JG/brulYmQ/uxti6qORLpN3Hgnvu7dgS0HmoG40kSLSq4Bs92qzIP64DFaUq+RBjrdXC5ItPnVAtFRZ1fwPmfdqeghmxrgOxaMKQnEp4N6ak60x9NNYo+7keArbkGOEGudiBQO2OF3oN7sjuYj1skYRlBuClFtbXXFy50japYfNyn3S/gRseAHZ8Nw5ltazrLu5ffFtDoF4zflzU/AA4dFQlosEO03LcK4HCqkVdW6ISwGMNjQAWnLOzV9fFlPKm9og/YeF1zoSQxWzqhnk4eoaXxhRLwxvFxbsuQUR0z+OPSyi1cAQwlTZQhBrLahxHnIFA90KNy3CLLXznYwpI1/aBUqbf/0j3gHvwy6GuDe1JWUlQKCxqvWdchOT5A4YPsYVUYGY2V0HvUIq2dHzqjvrl11Bk5r9ZFDgcIp343XJIMp9XBswE3eXRq7KtQdddwM5dX4XgyjfX7cDAdrZBZJct7Bv+Ackzod+O8zaoEpHRc8TyzTrygwYfTSba2hi0fyPYJsv+qtQ0lMIF/mFOOZCgQnZPtB9fp7eG+Ouc7gfR8AY+cHzvBC/AKgKgZE+XjK8MjoKNMujFKcCneY=
  app: project-m-front-end
  on:
    repo: PierreBtz/project-m
