language: node_js
node_js:
- 6
before_install:
- mkdir src/assets/private
- mkdir src/private
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/us.jpg.enc -out src/assets/private/us.jpg -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/lascanals.jpg.enc -out src/assets/private/lascanals.jpg -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/cityhall.png.enc -out src/assets/private/cityhall.png -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/church.png.enc -out src/assets/private/church.png -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/brunch.png.enc -out src/assets/private/brunch.png -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/secrets/location.json.enc -out src/private/location.json -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/secrets/secret-config.json.enc -out src/private/secret-config.json -d
install:
- npm install -g create-react-app
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: Q0Djyi2SOrxkkoPNbmTKM93hgzCtKxRUR3QPoRzW8/AlOH2MS4kgIAleVgn/qZMGR5XcT0SD1ZStpwffb6uHLoEfYXAbygxYHHYwCiEeK/3GyHiggbEDtCN5hCmr/6UUXIHlefusBEVY6cBu4n1hkBhCTtgb8KonNnLscgJDfovCU3yex99rbv5WYVgoZov2/CWiwQJ9QiQTNVwBtFPDJoLC7i32ZqcDfNnb1Afgi2pAxrD3/lB0MB/2BjI5djgqwX+GkBpFQHuvjphUpup4mwPamryZzugO8ouQHVUDM5e225+hjwM+mZ4KAp93zAQQWiO7AFmwsWIx3+f/ofzTXuKZ8bk1+KOy9eI3aNvR6avbkhTNnnyQKfj9/Ljay4LLjYSgkWUknDj72+qxgXe9ZioTJFCYQMH6pnLrLTMl8RbTNWvKgmptqzlmB6lQWnyxmFfPV1H2wzRbX7IlUKxNTsX8MZFsx9ABBL7MKzqFvmuIfvdJZdWFv63M9sPaw8ah70B6wKtqsjV2YJwUK5xm5+hiGZr1xf3/7f/E7xgUqAdW/gS+t7JrpLmft/X6cKqg5OpRM24j/E3rzFdsNQG2ZMoSTgxLB5rpJAuIqHt5VqHnQelAOMN9VAKWcDRB8R5aWgq7qQtBMMjlqI1PklqrIVjObolmZNzXv12VxzNdL7I=
  app: project-m-deployment
  on:
    repo: PierreBtz/project-m
