language: node_js
node_js:
- 6
before_install:
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/us.jpg.enc -out src/assets/private/us.jpg -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/lascanals.jpg.enc -out src/assets/private/lascanals.jpg -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/cityhall.png.enc -out src/assets/private/cityhall.png -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/church.png.enc -out src/assets/private/church.png -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/assets/secrets/brunch.png.enc -out src/assets/private/brunch.png -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/secrets/location.json.enc -out src/private/location.json -d
- openssl aes-256-cbc -K $encrypted_2e4c8f514f7d_key -iv $encrypted_2e4c8f514f7d_iv
  -in src/secrets/secret-config.json.enc -out src/private/secret-config.json -d

install:
- npm install
- npm run build
